version: '3.8'
services:
  frontend:
    image: frontend:latest
    ports:
      - "4200:4200"
    depends_on:
      - backend
    network_mode: "host"

  backend:
    image: backend:latest
    ports:
      - "8000:8000"
    environment:
      - DEBUG=True
      - DJANGO_ALLOWED_HOSTS=frontend,backend,localhost
    network_mode: "host"