version: '3.8'
services:
  frontend:
    image: frontend:latest
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - app-network

  backend:
    image: backend:latest
    ports:
      - "8000:8000"
    environment:
      - DEBUG=True
      - DJANGO_ALLOWED_HOSTS=frontend,backend,localhost
    networks:
      - app-network
    volumes:
      - ./db.sqlite3:/app/db.sqlite3  # TEMP for development

networks:
  app-network:
    driver: bridge