# Generated by Django 5.1.3 on 2024-12-07 12:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="status",
            name="active_state",
            field=models.BooleanField(
                default=True,
                help_text="An active status will be used to filter active tasks",
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="is_admin",
            field=models.BooleanField(
                default=False,
                help_text="Can access the admin part of the app to manage tasks",
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="is_member",
            field=models.BooleanField(default=False, help_text="Can access the app"),
        ),
        migrations.AlterField(
            model_name="task",
            name="estimated_duration",
            field=models.DurationField(default=datetime.timedelta(days=1)),
        ),
        migrations.AlterUniqueTogether(
            name="userassignment",
            unique_together={("user", "category")},
        ),
    ]
