# Generated by Django 5.1.3 on 2024-12-14 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_status_active_state_alter_customuser_is_admin_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="avatar",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="status",
            name="closed_state",
            field=models.BooleanField(
                default=False,
                help_text="A closed status will be used to filter closed tasks",
            ),
        ),
    ]
