# Generated by Django 5.1.3 on 2024-12-14 21:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_customuser_avatar_status_closed_state"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="task",
            name="assigned_user",
        ),
        migrations.RemoveField(
            model_name="task",
            name="description",
        ),
        migrations.RemoveField(
            model_name="task",
            name="title",
        ),
        migrations.AddField(
            model_name="task",
            name="comments",
            field=models.TextField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name="task",
            name="order",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="task",
            name="picked_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="assigned_user",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="reference",
            field=models.CharField(default="ABC-1234", max_length=64),
        ),
        migrations.AddField(
            model_name="task",
            name="reference_link",
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name="task",
            name="reserved_for_user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reserved_user",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
