# Generated by Django 5.1.3 on 2024-12-14 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "core",
            "0004_remove_task_assigned_user_remove_task_description_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="task",
            name="estimated_finalization",
        ),
    ]
