# Generated by Django 5.1.3 on 2024-12-16 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_project_trigram_status_blocked_state_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="status",
            name="active_state",
        ),
        migrations.RemoveField(
            model_name="status",
            name="blocked_state",
        ),
        migrations.RemoveField(
            model_name="status",
            name="closed_state",
        ),
        migrations.RemoveField(
            model_name="status",
            name="pending_state",
        ),
        migrations.AddField(
            model_name="project",
            name="order",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="status",
            name="state",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("active", "Active"),
                    ("closed", "Closed"),
                    ("blocked", "Blocked"),
                ],
                default="blocked",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="trigram",
            field=models.CharField(max_length=3, unique=True),
        ),
    ]
