# Generated by Django 5.1.3 on 2024-12-20 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0010_status_color"),
    ]

    operations = [
        migrations.AddField(
            model_name="status",
            name="dark_color",
            field=models.CharField(default="#000000", max_length=7),
        ),
    ]
