# Generated by Django 5.1.3 on 2024-12-22 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0011_status_dark_color"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="order",
            field=models.FloatField(null=True),
        ),
    ]
