# Generated by Django 5.1.3 on 2024-12-27 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0012_alter_task_order"),
    ]

    operations = [
        migrations.AlterField(
            model_name="status",
            name="dark_color",
            field=models.CharField(default="#FFFFFF", max_length=7),
        ),
    ]
