# Generated by Django 5.1.3 on 2025-01-02 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0014_workflowtransition"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customuser",
            name="is_admin",
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="is_member",
        ),
        migrations.AlterField(
            model_name="status",
            name="color",
            field=models.CharField(default="#FFFFFF", max_length=7),
        ),
        migrations.AlterField(
            model_name="status",
            name="dark_color",
            field=models.CharField(default="#000000", max_length=7),
        ),
    ]
