# Generated by Django 5.1.3 on 2025-01-04 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0015_remove_customuser_is_admin_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="TaskAudit",
        ),
    ]
