# Generated by Django 5.1.3 on 2025-01-04 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0016_delete_taskaudit"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="estimated_finalization",
            field=models.DateTimeField(null=True),
        ),
    ]
