# Generated by Django 5.1.3 on 2025-01-05 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0017_task_estimated_finalization"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="estimated_picked_at",
            field=models.DateTimeField(null=True),
        ),
    ]
