# Generated by Django 5.1.3 on 2025-02-01 13:05

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0018_task_estimated_picked_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="scheduleoverride",
            name="id",
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="schedulerule",
            name="id",
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
