# Generated by Django 5.1.5 on 2025-02-01 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0019_alter_scheduleoverride_id_alter_schedulerule_id"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="customuser",
            options={
                "permissions": [
                    ("change_someone_else_user", "Can update another user's profile"),
                    ("delete_someone_else_user", "Can delete another user's profile"),
                ]
            },
        ),
    ]
