# Generated by Django 5.1.5 on 2025-02-01 22:11

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0020_alter_customuser_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="task",
            options={"permissions": [("pick_task", "The user is allowed to pick a new task")]},
        ),
    ]
