# Generated by Django 5.1.3 on 2024-12-06 08:47

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("task_manager", "0003_useravailability"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="useravailability",
            unique_together={("user_id", "date")},
        ),
    ]
