# Generated by Django 5.1.3 on 2024-12-06 09:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("task_manager", "0004_alter_useravailability_unique_together"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ScheduleOverride",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(help_text="Specific date for the override")),
                (
                    "factor",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Override work factor for this date (e.g., 0.0 for no work, 1.0 for full-time)",
                        max_digits=3,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="schedule_overrides",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Schedule Override",
                "verbose_name_plural": "Schedule Overrides",
                "unique_together": {("user", "date")},
            },
        ),
        migrations.CreateModel(
            name="ScheduleRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "day_of_week",
                    models.IntegerField(
                        choices=[
                            (0, "Monday"),
                            (1, "Tuesday"),
                            (2, "Wednesday"),
                            (3, "Thursday"),
                            (4, "Friday"),
                            (5, "Saturday"),
                            (6, "Sunday"),
                        ],
                        help_text="Day of the week (0=Monday, 6=Sunday)",
                    ),
                ),
                (
                    "factor",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Work factor for this day (e.g., 0.0 for no work, 0.5 for half-time, 1.0 for full-time)",
                        max_digits=3,
                    ),
                ),
                (
                    "start_date",
                    models.DateField(
                        blank=True,
                        help_text="Optional start date for the rule",
                        null=True,
                    ),
                ),
                (
                    "end_date",
                    models.DateField(
                        blank=True,
                        help_text="Optional end date for the rule",
                        null=True,
                    ),
                ),
                (
                    "user_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="schedule_rules",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Schedule Rule",
                "verbose_name_plural": "Schedule Rules",
                "unique_together": {
                    ("user_id", "day_of_week", "start_date", "end_date")
                },
            },
        ),
        migrations.DeleteModel(
            name="UserAvailability",
        ),
    ]
