# Generated by Django 5.1.3 on 2024-12-06 09:05

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("task_manager", "0005_scheduleoverride_schedulerule_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name="scheduleoverride",
            old_name="user",
            new_name="user_id",
        ),
        migrations.AlterUniqueTogether(
            name="scheduleoverride",
            unique_together={("user_id", "date")},
        ),
    ]
