# Generated by Django 5.1.3 on 2024-12-16 20:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("task_manager", "0005_remove_task_estimated_finalization"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="trigram",
            field=models.CharField(max_length=3, null=True),
        ),
        migrations.AddField(
            model_name="status",
            name="blocked_state",
            field=models.BooleanField(
                default=False,
                help_text="A blocked status will be used to filter blocked tasks",
            ),
        ),
        migrations.AddField(
            model_name="status",
            name="pending_state",
            field=models.BooleanField(
                default=False,
                help_text="A pending status will be used to filter pending tasks",
            ),
        ),
        migrations.AlterField(
            model_name="status",
            name="active_state",
            field=models.BooleanField(
                default=False,
                help_text="An active status will be used to filter active tasks",
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="picked_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="picked_by",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="reserved_for_user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reserved_for_user",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
