# Generated by Django 5.1.3 on 2024-12-06 15:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("task_manager", "0006_rename_user_scheduleoverride_user_id_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="project",
            name="team_id",
        ),
        migrations.AlterUniqueTogether(
            name="teamassignment",
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name="teamassignment",
            name="user_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                unique=True,
            ),
        ),
        migrations.RemoveField(
            model_name="teamassignment",
            name="team_id",
        ),
        migrations.DeleteModel(
            name="Team",
        ),
    ]
