# Generated by Django 5.1.3 on 2024-12-19 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("task_manager", "0008_task_created_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="categories",
            field=models.ManyToManyField(
                through="task_manager.UserAssignment", to="task_manager.category"
            ),
        ),
    ]
