# Generated by Django 5.1.3 on 2024-12-20 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("task_manager", "0009_customuser_categories"),
    ]

    operations = [
        migrations.AddField(
            model_name="status",
            name="color",
            field=models.CharField(default="#000000", max_length=7),
        ),
    ]
